# Generated by Django 5.0.1 on 2024-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={'verbose_name': 'Group chat', 'verbose_name_plural': 'Group chats'},
        ),
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'verbose_name': 'Group message', 'verbose_name_plural': 'Group messages'},
        ),
        migrations.AddField(
            model_name='groupchat',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/avatar.jpg', null=True, upload_to='image/', verbose_name='Avatar'),
        ),
    ]
