# Generated by Django 5.0.1 on 2024-02-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0002_alter_groupchat_options_alter_groupmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_group.png', null=True, upload_to='image/', verbose_name='Avatar'),
        ),
    ]
