# Generated by Django 5.0.1 on 2024-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/avatar.jpg', null=True, upload_to='image/', verbose_name='Avatar'),
        ),
    ]
